# Updated: 2024-06-27
# Site settings
title: "Statamic to Saleor Migration"
description: "Documentation for the migration from Statamic CMS to Saleor headless commerce platform"
repository: mprolabs/statamic-to-saleor-migration
baseurl: "/statamic-to-saleor-migration"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.6.1
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-seo-tag

# Just the Docs theme configuration
# See: https://just-the-docs.com/docs/configuration/
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
enable_copy_code_button: true
color_scheme: light
aux_links:
  "View on GitHub":
    - "//github.com/mprolabs/statamic-to-saleor-migration"
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2024 MPROLabs. All rights reserved."

# Mermaid diagram support
mermaid:
  version: "10.9.0"

# Collections (documentation sections)
collections:
  architecture:
    permalink: "/architecture/:name/"
    output: true
  migration:
    permalink: "/migration/:name/"
    output: true
  multi-region-language:
    permalink: "/multi-region-language/:name/"
    output: true
  development:
    permalink: "/development/:name/"
    output: true

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "architecture"
    values:
      layout: "default"
  - scope:
      path: "migration"
    values:
      layout: "default"
  - scope:
      path: "multi-region-language"
    values:
      layout: "default"
  - scope:
      path: "development"
    values:
      layout: "default"
  - scope:
      path: "development/index.md"
    values:
      permalink: "/development/"
  - scope:
      path: "multi-region-language/index.md"
    values:
      permalink: "/multi-region-language/"
  - scope:
      path: "architecture/index.md"
    values:
      permalink: "/architecture/"
  - scope:
      path: "migration/index.md"
    values:
      permalink: "/migration/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .git
  - .github
  - README.md

# Include additional directories
include:
  - assets

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Google Analytics
# ga_tracking: UA-5555555-5
# ga_tracking_anonymize_ip: true

# Navigation
header_pages:
  - architecture/index.md
  - migration/index.md
  - multi-region-language/index.md
  - development/index.md 