# Updated: 2024-06-25
# Site settings
title: "Statamic to Saleor Migration"
description: "Documentation for the migration from Statamic CMS to Saleor headless commerce platform"
repository: mprolabs/statamic-to-saleor-migration
baseurl: "/statamic-to-saleor-migration"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata

# Theme customization
show_downloads: false

# Theme configuration
theme: just-the-docs
color_scheme: light

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search
search_tokenizer_separator: /[\s/]+/

# Heading anchor links appear on hover
heading_anchors: true

# Enable copy code button for code blocks
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2023 MPROLabs. All rights reserved."

# Navigation structure
nav:
  - title: Home
    url: /
  - title: Architecture
    url: /architecture/
  - title: Migration
    url: /migration/
  - title: Development
    url: /development/

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Google Analytics
# ga_tracking: UA-5555555-5
# ga_tracking_anonymize_ip: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github

# Navigation
header_pages:
  - architecture/index.md
  - migration/index.md
  - multi-region-language/index.md
  - development/index.md

# Include additional directories
include:
  - assets
  - _data

# Define collections if needed
collections:
  architecture:
    permalink: "/:collection/:path/"
    output: true
  migration:
    permalink: "/:collection/:path/"
    output: true
  development:
    permalink: "/:collection/:path/"
    output: true

# Default front matter for pages
defaults:
  -
    scope:
      path: ""
      type: "architecture"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "migration"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "development"
    values:
      layout: "default" 