source "https://rubygems.org"

# Use the latest version of Jekyll
gem "jekyll", "~> 4.3.2"

# Use the just-the-docs theme
gem "just-the-docs", "~> 0.5.0"

# Plugins used by the site
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "jekyll-include-cache", "~> 0.2.1"

# Windows and JRuby support
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance tools
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "webrick", "~> 1.8" 