source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "just-the-docs", "0.6.1"
gem "jekyll-github-metadata"
gem "webrick", "~> 1.9"
gem "google-protobuf", "3.21.12", platforms: :ruby
gem "sass-embedded", "~> 1.58.3"
gem "ffi", "~> 1.15.5" 