name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
    paths:
      - 'docs/**'
      - 'src/architecture/diagrams/**'
      - '.github/workflows/github-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # If using PlantUML diagrams, install Java and PlantUML
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      # Update diagrams from source if needed
      - name: Generate diagrams
        run: |
          cd src/architecture/diagrams
          chmod +x render.sh
          ./render.sh
          mkdir -p ../../../docs/architecture/diagrams/
          cp *.png *.svg ../../../docs/architecture/diagrams/
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: docs
      
      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install
      
      - name: Build site
        run: |
          cd docs
          bundle exec jekyll build
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 